# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: Fun python
subtitle: Funny Samples with python
description: Funny Samples with python
author: RunAtWorld
language:
timezone:

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: /
root: "/"
permalink: :year/:month/:day/:title/
permalink_defaults:

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
about_dir: about
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace:

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: ils

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  type:
# theme basic info
# ä¸»é¢˜åŸºæœ¬ä¿¡æ¯ï¼Œæ— éœ€æ”¹åŠ¨ã€‚
theme_info:
  name: ILS
  version: 1.1.2
  author: XPoet
  repository: https://github.com/XPoet/hexo-theme-ils

# favicon
# ç½‘ç«™å›¾æ ‡ï¼Œè¯·åœ¨ "/source/images/" ç›®å½•ï¼Œæ¢æˆè‡ªå·±çš„å³å¯ã€‚
favicon: images/favicon.png

# avatar
# å¤´åƒå›¾ç‰‡ï¼Œè¯·åœ¨ "/source/images/" ç›®å½•ï¼Œæ¢æˆè‡ªå·±çš„å³å¯ã€‚
avatar: images/avatar.png

# navigation menu
# å¯¼èˆªèœå•ï¼Œå¦‚éœ€æ–°å¢å¯¼èˆªï¼Œè¯·æŒ‰ä¸‹é¢æ ¼å¼å¡«å†™ï¼ŒåŒæ—¶éœ€è¦æ·»åŠ å¯¹åº”çš„ Hexo é¡µé¢ã€‚
# æ–°å¢é¡µé¢ï¼Œè¯·å‚è€ƒå¾€ä¸‹çš„æ•™ç¨‹ï¼š"Add page æ·»åŠ é¡µé¢"ã€‚
menu:
  Home: /
  Archives: /archives
  # About: /about
  # Links: /links
  # ...

# RSS
# RSS è®¢é˜…ï¼Œå¦‚éœ€å¯ç”¨ï¼Œè¯·å…ˆå®‰è£… Hexo æ’ä»¶ï¼šhexo-generator-feedã€‚
rss:
  enable: true

# comment plugin
# è¯„è®ºæ’ä»¶ï¼Œä¸»é¢˜å†…ç½®äº† Valine å’Œ Gitalkï¼Œåªèƒ½ä½¿ç”¨å…¶ä¸­ä¸€æ¬¾ï¼Œå¦‚æœ enable éƒ½è®¾ä¸ºäº† trueï¼Œå°†ä½¿ç”¨ Valineã€‚
comments:
  # Valine https://github.com/xCss/Valine
  # å¦‚ä½•ä½¿ç”¨ Valine è¯·å‚è€ƒï¼šhttps://github.com/xCss/Valine
  valine:
    enable: false
    appid:   # leancloud appid
    appkey:  # leancloud appkey
    meta: ['nick', 'mail', 'link']
    placeholder: ğŸ˜œå°½æƒ…åæ§½å§~

  # Gitalk https://github.com/gitalk/gitalk
  # å¦‚ä½•ä½¿ç”¨ Gitalk è¯·å‚è€ƒï¼šhttps://github.com/gitalk/gitalk
  gitalk:
    enable: false
    github_id:      # GitHub repo owner
    repository:     # Repository name to store issues
    client_id:      # GitHub Application Client ID
    client_secret:  # GitHub Application Client Secret

# website count
# ç½‘ç«™è®¡æ•°
website_count:
  # busuanzi http://ibruce.info/2015/04/04/busuanzi/
  busuanzi_count:
    enable: false
    site_uv: false
    site_pv: false
    page_pv: false

# Local Search
# Dependencies: https://github.com/theme-next/hexo-generator-searchdb
# æœ¬åœ°æœç´¢ï¼Œå¦‚éœ€å¯ç”¨ï¼Œè¯·å…ˆå®‰è£… Hexo æ’ä»¶ï¼šhexo-generator-searchdbã€‚
local_search:
  enable: true

  # If auto, trigger search by changing input.
  # If manual, trigger search by pressing enter key or search button.
  # è¾“å…¥å…³é”®å­—åçš„è§¦å‘æœç´¢ï¼Œå¯é€‰ è‡ªåŠ¨ auto æˆ– æ‰‹åŠ¨ manualã€‚
  # auto æ¯è¾“å…¥æˆ–åˆ é™¤ä¸€ä¸ªå­—ç¬¦åï¼Œè‡ªåŠ¨è§¦å‘æœç´¢ã€‚
  # manual æ¯è¾“å…¥æˆ–åˆ é™¤ä¸€ä¸ªå­—ç¬¦åï¼Œéœ€è¦æŒ‰å›è½¦é”®è§¦å‘æœç´¢ã€‚
  trigger: auto  # values: auto | manual

  # Unescape html strings to the readable one.
  # è½¬ä¹‰ HTML å­—ç¬¦ä¸²ä¸ºå¯è¯»å­—ç¬¦ä¸²ã€‚
  unescape: false

  # Preload the search data when the page loads.
  # åœ¨é¡µé¢åŠ è½½æ—¶é¢„åŠ è½½æœç´¢æ•°æ®
  preload: true


search:
  path: search.json
  field: post
  content: true
  format: striptags

# Code Copy
# ä»£ç å¤åˆ¶ï¼Œå¤åˆ¶é£æ ¼å¯é€‰ default | flat | macã€‚
code_copy:
  enable: true
  style: flat  # values: default | flat | mac

# sidebar tools
# ä¾§è¾¹æ å·¥å…·ï¼Œä½ç½®å¯é€‰ left | rightã€‚
side_tools:
  enable: true
  position: right  # values: left | right

# back to top
# å›åˆ°é¡¶éƒ¨ï¼Œä½ç½®å¯é€‰ left | rightã€‚
back2top:
  enable: true
  position: right  # values: left | right

# Table of Contents in the Sidebar
# æ–‡ç« ç›®å½•ç»“æ„
toc:
  enable: true

  # Automatically add list number to toc.
  # ç»™æ–‡ç« ç›®å½•è‡ªåŠ¨åŠ ä¸Šåºå·ã€‚
  number: true

  # If true, all level of TOC in a post will be displayed, rather than the activated part of it.
  # æ˜¯å¦å±•å¼€æ‰€æœ‰ç›®å½•
  expand_all: true

# magic 
# magic ä¸º v1.1.0 å¢åŠ çš„æ–°ç‰¹æ€§ï¼Œå¯ç”¨åï¼Œä¸»é¢˜æ ·å¼å°†ä»¥ç®€çº¦çš„å¡ç‰‡å½¢å¼æ˜¾ç¤ºã€‚
magic:
  enable: true  # æ˜¯å¦å¼€å¯ magic é£æ ¼
  scale: false  # æ˜¯å¦å¼€å¯ç¼©æ”¾æ•ˆæœ
  shadow: true  # æ˜¯å¦å¼€å¯é˜´å½±æ•ˆæœ
  sidebar:
    enable: false # æ˜¯å¦æ˜¾ç¤ºä¾§è¾¹æ 
    fixed: true  # ä¾§è¾¹æ æ˜¯å¦å›ºå®š
    position: right  # ä¾§è¾¹æ ä½ç½® values: left | right

# æ–‡ç« å­—æ•°ç»Ÿè®¡ã€é˜…è¯»æ—¶é•¿
# éœ€è¦å®‰è£… https://github.com/willin/hexo-wordcount
# npm i --save hexo-wordcount
post_wordcount:
  wordcount: true  # å­—æ•°ç»Ÿè®¡
  min2read: true   # é˜…è¯»æ—¶é•¿